DEBUG 2019-06-28 21:32:51,695: 	 Executing command: 'submit'
DEBUG 2019-06-28 21:32:51,697: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-06-28 21:32:51,777: 	 Checking credentials
DEBUG 2019-06-28 21:32:51,778: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-06-28 21:32:51,778: 	 Getting proxy life time left
DEBUG 2019-06-28 21:32:52,482: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43004

 error: 
 retcode : 0
DEBUG 2019-06-28 21:32:53,089: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43003

 error: 
 retcode : 0
DEBUG 2019-06-28 21:32:53,089: 	 Proxy lifetime 43004 secs is different from voms extension lifetime 43003 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-06-28 21:32:53,089: 	 Proxy valid for 11:56:43 hours
INFO 2019-06-28 21:32:53,089: 	 Will use CRAB configuration file crab_MC.py
DEBUG 2019-06-28 21:32:53,089: 	 Loading CRAB configuration file.
ERROR 2019-06-28 21:32:55,381: 	 Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-06-28 21:32:55,381: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-06-28 21:49:40,514: 	 Executing command: 'submit'
DEBUG 2019-06-28 21:49:40,514: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-06-28 21:49:40,522: 	 Checking credentials
DEBUG 2019-06-28 21:49:40,523: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-06-28 21:49:40,523: 	 Getting proxy life time left
DEBUG 2019-06-28 21:49:41,227: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 41995

 error: 
 retcode : 0
DEBUG 2019-06-28 21:49:41,840: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 41995

 error: 
 retcode : 0
DEBUG 2019-06-28 21:49:41,840: 	 Proxy valid for 11:39:55 hours
INFO 2019-06-28 21:49:41,840: 	 Will use CRAB configuration file crab_MC.py
DEBUG 2019-06-28 21:49:41,840: 	 Loading CRAB configuration file.
DEBUG 2019-06-28 21:49:44,325: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-06-28 21:49:44,327: 	 Working area '/afs/cern.ch/work/s/sukundu/private/Run_PYTHIA8_V1/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_2017_PY_flat_15_7000Charge_analysis' already exists 
Please change the requestName in the config file
ERROR 2019-06-28 21:49:44,327: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/Run_PYTHIA8_V1/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_2017_PY_flat_15_7000Charge_analysis' already exists 
Please change the requestName in the config file
DEBUG 2019-06-28 21:50:35,604: 	 Executing command: 'submit'
DEBUG 2019-06-28 21:50:35,604: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-06-28 21:50:35,611: 	 Checking credentials
DEBUG 2019-06-28 21:50:35,611: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-06-28 21:50:35,611: 	 Getting proxy life time left
DEBUG 2019-06-28 21:50:36,216: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 41940

 error: 
 retcode : 0
DEBUG 2019-06-28 21:50:36,925: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 41940

 error: 
 retcode : 0
DEBUG 2019-06-28 21:50:36,925: 	 Proxy valid for 11:39:00 hours
INFO 2019-06-28 21:50:36,925: 	 Will use CRAB configuration file crab_MC.py
DEBUG 2019-06-28 21:50:36,925: 	 Loading CRAB configuration file.
DEBUG 2019-06-28 21:50:39,340: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-06-28 21:50:39,341: 	 Working area '/afs/cern.ch/work/s/sukundu/private/Run_PYTHIA8_V1/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_2017_PY_flat_15_7000Charge_analysis' already exists 
Please change the requestName in the config file
ERROR 2019-06-28 21:50:39,341: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/Run_PYTHIA8_V1/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_2017_PY_flat_15_7000Charge_analysis' already exists 
Please change the requestName in the config file
DEBUG 2019-06-29 08:23:04,073: 	 Executing command: 'submit'
DEBUG 2019-06-29 08:23:04,073: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-06-29 08:23:04,081: 	 Checking credentials
DEBUG 2019-06-29 08:23:04,082: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-06-29 08:23:04,082: 	 Getting proxy life time left
DEBUG 2019-06-29 08:23:04,787: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43186

 error: 
 retcode : 0
DEBUG 2019-06-29 08:23:05,493: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43185

 error: 
 retcode : 0
DEBUG 2019-06-29 08:23:05,494: 	 Proxy lifetime 43186 secs is different from voms extension lifetime 43185 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-06-29 08:23:05,494: 	 Proxy valid for 11:59:45 hours
INFO 2019-06-29 08:23:05,494: 	 Will use CRAB configuration file crab_MC.py
DEBUG 2019-06-29 08:23:05,494: 	 Loading CRAB configuration file.
ERROR 2019-06-29 08:23:08,073: 	 Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-06-29 08:23:08,073: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 16:12:22,188: 	 Executing command: 'submit'
DEBUG 2019-08-16 16:12:22,191: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 16:12:22,227: 	 Checking credentials
DEBUG 2019-08-16 16:12:22,228: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 16:12:22,228: 	 Getting proxy life time left
DEBUG 2019-08-16 16:12:23,143: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43171

 error: 
 retcode : 0
DEBUG 2019-08-16 16:12:24,062: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43171

 error: 
 retcode : 0
DEBUG 2019-08-16 16:12:24,063: 	 Proxy valid for 11:59:31 hours
INFO 2019-08-16 16:12:24,063: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 16:12:24,063: 	 Loading CRAB configuration file.
ERROR 2019-08-16 16:12:27,270: 	 Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 16:12:27,270: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.publishDataName has been renamed to Data.outputDatasetTag starting from CRAB v3.3.1511; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 16:16:56,027: 	 Executing command: 'submit'
DEBUG 2019-08-16 16:16:56,028: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 16:16:56,035: 	 Checking credentials
DEBUG 2019-08-16 16:16:56,036: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 16:16:56,036: 	 Getting proxy life time left
DEBUG 2019-08-16 16:16:56,742: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 42898

 error: 
 retcode : 0
DEBUG 2019-08-16 16:16:57,448: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 42897

 error: 
 retcode : 0
DEBUG 2019-08-16 16:16:57,448: 	 Proxy lifetime 42898 secs is different from voms extension lifetime 42897 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-16 16:16:57,448: 	 Proxy valid for 11:54:57 hours
INFO 2019-08-16 16:16:57,449: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 16:16:57,449: 	 Loading CRAB configuration file.
ERROR 2019-08-16 16:17:02,563: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 16:17:02,563: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:11:18,501: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:11:18,503: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:11:18,513: 	 Checking credentials
DEBUG 2019-08-16 18:11:18,514: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:11:18,514: 	 Getting proxy life time left
DEBUG 2019-08-16 18:11:19,218: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 36035

 error: 
 retcode : 0
DEBUG 2019-08-16 18:11:19,924: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 36035

 error: 
 retcode : 0
DEBUG 2019-08-16 18:11:19,924: 	 Proxy valid for 10:00:35 hours
INFO 2019-08-16 18:11:19,924: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:11:19,924: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:11:19,954: 	 Error while loading CRAB configuration:
name 'getUsernameFromSiteDB' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:11:19,954: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'getUsernameFromSiteDB' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:12:45,501: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:12:45,501: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:12:45,510: 	 Checking credentials
DEBUG 2019-08-16 18:12:45,511: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:12:45,511: 	 Getting proxy life time left
DEBUG 2019-08-16 18:12:46,216: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35948

 error: 
 retcode : 0
DEBUG 2019-08-16 18:12:46,923: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35948

 error: 
 retcode : 0
DEBUG 2019-08-16 18:12:46,923: 	 Proxy valid for 09:59:08 hours
INFO 2019-08-16 18:12:46,923: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:12:46,923: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:12:46,928: 	 Error while loading CRAB configuration:
name 'Configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:12:46,928: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'Configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:13:47,895: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:13:47,895: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:13:47,901: 	 Checking credentials
DEBUG 2019-08-16 18:13:47,902: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:13:47,902: 	 Getting proxy life time left
DEBUG 2019-08-16 18:13:48,506: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35886

 error: 
 retcode : 0
DEBUG 2019-08-16 18:13:49,210: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35885

 error: 
 retcode : 0
DEBUG 2019-08-16 18:13:49,210: 	 Proxy lifetime 35886 secs is different from voms extension lifetime 35885 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-16 18:13:49,210: 	 Proxy valid for 09:58:05 hours
INFO 2019-08-16 18:13:49,211: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:13:49,211: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:13:54,297: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:13:54,297: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:20:47,220: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:20:47,221: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:20:47,229: 	 Checking credentials
DEBUG 2019-08-16 18:20:47,229: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:20:47,229: 	 Getting proxy life time left
DEBUG 2019-08-16 18:20:47,934: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35467

 error: 
 retcode : 0
DEBUG 2019-08-16 18:20:48,639: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35466

 error: 
 retcode : 0
DEBUG 2019-08-16 18:20:48,639: 	 Proxy lifetime 35467 secs is different from voms extension lifetime 35466 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-16 18:20:48,639: 	 Proxy valid for 09:51:06 hours
INFO 2019-08-16 18:20:48,640: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:20:48,640: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:20:53,507: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:20:53,508: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:22:01,091: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:22:01,091: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:22:01,098: 	 Checking credentials
DEBUG 2019-08-16 18:22:01,098: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:22:01,098: 	 Getting proxy life time left
DEBUG 2019-08-16 18:22:01,802: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35393

 error: 
 retcode : 0
DEBUG 2019-08-16 18:22:02,507: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35392

 error: 
 retcode : 0
DEBUG 2019-08-16 18:22:02,507: 	 Proxy lifetime 35393 secs is different from voms extension lifetime 35392 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-16 18:22:02,508: 	 Proxy valid for 09:49:52 hours
INFO 2019-08-16 18:22:02,508: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:22:02,508: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:22:07,507: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:22:07,508: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:22:38,506: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:22:38,506: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:22:38,514: 	 Checking credentials
DEBUG 2019-08-16 18:22:38,515: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:22:38,515: 	 Getting proxy life time left
DEBUG 2019-08-16 18:22:39,121: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35355

 error: 
 retcode : 0
DEBUG 2019-08-16 18:22:39,730: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35355

 error: 
 retcode : 0
DEBUG 2019-08-16 18:22:39,731: 	 Proxy valid for 09:49:15 hours
INFO 2019-08-16 18:22:39,731: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:22:39,731: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:22:44,539: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:22:44,539: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 18:23:14,633: 	 Executing command: 'submit'
DEBUG 2019-08-16 18:23:14,633: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 18:23:14,640: 	 Checking credentials
DEBUG 2019-08-16 18:23:14,640: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 18:23:14,640: 	 Getting proxy life time left
DEBUG 2019-08-16 18:23:15,345: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35319

 error: 
 retcode : 0
DEBUG 2019-08-16 18:23:16,050: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35319

 error: 
 retcode : 0
DEBUG 2019-08-16 18:23:16,050: 	 Proxy valid for 09:48:39 hours
INFO 2019-08-16 18:23:16,050: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-16 18:23:16,050: 	 Loading CRAB configuration file.
ERROR 2019-08-16 18:23:23,259: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 18:23:23,259: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-16 19:59:23,591: 	 Executing command: 'submit'
DEBUG 2019-08-16 19:59:23,592: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-16 19:59:23,650: 	 Checking credentials
DEBUG 2019-08-16 19:59:23,651: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-16 19:59:23,651: 	 Getting proxy life time left
DEBUG 2019-08-16 19:59:24,456: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 29550

 error: 
 retcode : 0
DEBUG 2019-08-16 19:59:25,161: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 29549

 error: 
 retcode : 0
DEBUG 2019-08-16 19:59:25,162: 	 Proxy lifetime 29550 secs is different from voms extension lifetime 29549 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-16 19:59:25,162: 	 Proxy valid for 08:12:29 hours
INFO 2019-08-16 19:59:25,163: 	 Will use CRAB configuration file crab_MC.py
DEBUG 2019-08-16 19:59:25,163: 	 Loading CRAB configuration file.
ERROR 2019-08-16 19:59:27,572: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-16 19:59:27,573: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-21 12:48:44,859: 	 Executing command: 'submit'
DEBUG 2019-08-21 12:48:44,860: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-21 12:48:44,868: 	 Checking credentials
DEBUG 2019-08-21 12:48:44,869: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-21 12:48:44,869: 	 Getting proxy life time left
DEBUG 2019-08-21 12:48:45,574: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35747

 error: 
 retcode : 0
DEBUG 2019-08-21 12:48:46,281: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35746

 error: 
 retcode : 0
DEBUG 2019-08-21 12:48:46,281: 	 Proxy lifetime 35747 secs is different from voms extension lifetime 35746 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-21 12:48:46,281: 	 Proxy valid for 09:55:46 hours
INFO 2019-08-21 12:48:46,281: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-21 12:48:46,282: 	 Loading CRAB configuration file.
ERROR 2019-08-21 12:48:48,825: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-21 12:48:48,825: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-21 12:49:27,051: 	 Executing command: 'submit'
DEBUG 2019-08-21 12:49:27,051: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-21 12:49:27,059: 	 Checking credentials
DEBUG 2019-08-21 12:49:27,060: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-21 12:49:27,060: 	 Getting proxy life time left
DEBUG 2019-08-21 12:49:27,765: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35705

 error: 
 retcode : 0
DEBUG 2019-08-21 12:49:28,471: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35704

 error: 
 retcode : 0
DEBUG 2019-08-21 12:49:28,471: 	 Proxy lifetime 35705 secs is different from voms extension lifetime 35704 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-21 12:49:28,471: 	 Proxy valid for 09:55:04 hours
INFO 2019-08-21 12:49:28,471: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-21 12:49:28,471: 	 Loading CRAB configuration file.
DEBUG 2019-08-21 12:49:31,018: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-08-21 12:49:31,019: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
ERROR 2019-08-21 12:49:31,019: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
DEBUG 2019-08-21 12:53:06,064: 	 Executing command: 'submit'
DEBUG 2019-08-21 12:53:06,064: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-21 12:53:06,081: 	 Checking credentials
DEBUG 2019-08-21 12:53:06,081: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-21 12:53:06,081: 	 Getting proxy life time left
DEBUG 2019-08-21 12:53:06,888: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35486

 error: 
 retcode : 0
DEBUG 2019-08-21 12:53:07,596: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35485

 error: 
 retcode : 0
DEBUG 2019-08-21 12:53:07,596: 	 Proxy lifetime 35486 secs is different from voms extension lifetime 35485 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-21 12:53:07,596: 	 Proxy valid for 09:51:25 hours
INFO 2019-08-21 12:53:07,596: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-21 12:53:07,597: 	 Loading CRAB configuration file.
ERROR 2019-08-21 12:53:10,108: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-08-21 12:53:10,109: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 10 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-08-21 12:54:49,463: 	 Executing command: 'submit'
DEBUG 2019-08-21 12:54:49,464: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-21 12:54:49,474: 	 Checking credentials
DEBUG 2019-08-21 12:54:49,474: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-21 12:54:49,475: 	 Getting proxy life time left
DEBUG 2019-08-21 12:54:50,180: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 35382

 error: 
 retcode : 0
DEBUG 2019-08-21 12:54:50,886: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 35382

 error: 
 retcode : 0
DEBUG 2019-08-21 12:54:50,886: 	 Proxy valid for 09:49:42 hours
INFO 2019-08-21 12:54:50,886: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-21 12:54:50,886: 	 Loading CRAB configuration file.
DEBUG 2019-08-21 12:54:53,335: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-08-21 12:54:53,337: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
ERROR 2019-08-21 12:54:53,337: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
DEBUG 2019-08-21 13:48:28,905: 	 Executing command: 'submit'
DEBUG 2019-08-21 13:48:28,905: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-21 13:48:28,913: 	 Checking credentials
DEBUG 2019-08-21 13:48:28,914: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-21 13:48:28,914: 	 Getting proxy life time left
DEBUG 2019-08-21 13:48:29,724: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 42399

 error: 
 retcode : 0
DEBUG 2019-08-21 13:48:30,432: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 42398

 error: 
 retcode : 0
DEBUG 2019-08-21 13:48:30,433: 	 Proxy lifetime 42399 secs is different from voms extension lifetime 42398 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-21 13:48:30,433: 	 Proxy valid for 11:46:38 hours
INFO 2019-08-21 13:48:30,433: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-21 13:48:30,433: 	 Loading CRAB configuration file.
DEBUG 2019-08-21 13:48:33,263: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-08-21 13:48:33,265: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
ERROR 2019-08-21 13:48:33,265: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
DEBUG 2019-08-22 12:31:48,263: 	 Executing command: 'submit'
DEBUG 2019-08-22 12:31:48,264: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2019-08-22 12:31:48,274: 	 Checking credentials
DEBUG 2019-08-22 12:31:48,274: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2019-08-22 12:31:48,274: 	 Getting proxy life time left
DEBUG 2019-08-22 12:31:48,980: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43178

 error: 
 retcode : 0
DEBUG 2019-08-22 12:31:49,689: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43177

 error: 
 retcode : 0
DEBUG 2019-08-22 12:31:49,689: 	 Proxy lifetime 43178 secs is different from voms extension lifetime 43177 secs for proxy: /tmp/x509up_u107261
DEBUG 2019-08-22 12:31:49,689: 	 Proxy valid for 11:59:37 hours
INFO 2019-08-22 12:31:49,690: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2019-08-22 12:31:49,690: 	 Loading CRAB configuration file.
DEBUG 2019-08-22 12:31:52,303: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-08-22 12:31:52,305: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
ERROR 2019-08-22 12:31:52,305: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_Charge_Jet/CMSSW_9_4_6/src/Test/QCDEventShape/test/crab_projects/crab_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8' already exists 
Please change the requestName in the config file
